/* ============================================================
 * birthdays.js —— 角色生日数据（扩充版）
 * 广义二次元：动漫、漫画、游戏、虚拟歌手等 + 经典影视剧角色
 * 生日取官方设定生日 / 官方资料公布的纪念日；仅收录确定度较高的条目
 * 字段：m(月) d(日) name(角色) work(所属作品/企划)
 * 数据可能有出入，欢迎校对补充
 * ============================================================ */
window.BIRTHDAYS = [
  { m: 1, d: 1, name: '波特卡斯·D·艾斯', work: '航海王' },
  { m: 1, d: 1, name: '流川枫', work: '灌篮高手' },
  { m: 1, d: 1, name: '四宫辉夜', work: '辉夜大小姐想让我告白' },
  { m: 1, d: 1, name: '壬氏', work: '药屋少女的呢喃' },
  { m: 1, d: 1, name: '东峰旭', work: '排球少年' },
  { m: 1, d: 1, name: '黑泽黛雅', work: 'Love Live! Sunshine!!' },
  { m: 1, d: 1, name: '久川铁道', work: '未闻花名' },
  { m: 1, d: 2, name: '蜘蛛（瓦尔莱塔）', work: '第五人格' },
  { m: 1, d: 2, name: '市谷有咲', work: 'BanG Dream!' },
  { m: 1, d: 2, name: '阿笠博士', work: '名侦探柯南' },
  { m: 1, d: 3, name: '流浪者', work: '原神' },
  { m: 1, d: 3, name: '白术', work: '原神' },
  { m: 1, d: 3, name: '鹿野院平藏', work: '原神' },
  { m: 1, d: 3, name: '咒术师', work: '第五人格' },
  { m: 1, d: 5, name: '白鹭千圣', work: 'BanG Dream!' },
  { m: 1, d: 6, name: '夏洛克·福尔摩斯', work: '福尔摩斯探案' },
  { m: 1, d: 9, name: '白', work: '火影忍者' },
  { m: 1, d: 9, name: '西弗勒斯·斯内普', work: '哈利·波特' },
  { m: 1, d: 10, name: '尤斯塔斯·基德', work: '航海王' },
  { m: 1, d: 11, name: '莱依拉', work: '原神' },
  { m: 1, d: 11, name: '轰焦冻', work: '我的英雄学院' },
  { m: 1, d: 12, name: '律师（弗雷迪·莱利）', work: '第五人格' },
  { m: 1, d: 13, name: '盲女（海伦娜·亚当斯）', work: '第五人格' },
  { m: 1, d: 15, name: '秋山澪', work: '轻音少女' },
  { m: 1, d: 15, name: '花园多惠', work: 'BanG Dream!' },
  { m: 1, d: 17, name: '小泉花阳', work: 'Love Live!' },
  { m: 1, d: 19, name: '我爱罗', work: '火影忍者' },
  { m: 1, d: 20, name: '禅院真希', work: '咒术回战' },
  { m: 1, d: 21, name: '申鹤', work: '原神' },
  { m: 1, d: 23, name: '油女志乃', work: '火影忍者' },
  { m: 1, d: 23, name: '冰河', work: '圣斗士星矢' },
  { m: 1, d: 24, name: '黄衣之主（哈斯塔）', work: '第五人格' },
  { m: 1, d: 25, name: '波风水门', work: '火影忍者' },
  { m: 1, d: 25, name: '大和赤骥', work: '赛马娘' },
  { m: 1, d: 27, name: '千织', work: '原神' },
  { m: 1, d: 27, name: 'IA', work: 'VOCALOID · 1st Place' },
  { m: 1, d: 30, name: '巡音流歌', work: 'VOCALOID · 巡音ルカ' },
  { m: 1, d: 31, name: '黑子哲也', work: '黑子的篮球' },
  { m: 1, d: 31, name: '狼嵜光', work: '金牌得主' },
  { m: 1, d: 31, name: '朽木白哉', work: 'BLEACH' },
  { m: 2, d: 1, name: '克洛琳德', work: '原神' },
  { m: 2, d: 1, name: '祭司（菲欧娜·吉尔曼）', work: '第五人格' },
  { m: 2, d: 2, name: '蕾姆 / 拉姆', work: 'Re:从零开始的异世界生活' },
  { m: 2, d: 2, name: '松冈凛', work: 'Free!' },
  { m: 2, d: 2, name: '平泽忧', work: '轻音少女' },
  { m: 2, d: 3, name: '夏油杰', work: '咒术回战' },
  { m: 2, d: 3, name: '远坂凛', work: 'Fate/stay night' },
  { m: 2, d: 3, name: '菲伦', work: '葬送的芙莉莲' },
  { m: 2, d: 5, name: '蒙奇·D·龙', work: '航海王' },
  { m: 2, d: 6, name: '妮可·罗宾', work: '航海王' },
  { m: 2, d: 7, name: '富冈义勇', work: '鬼灭之刃' },
  { m: 2, d: 8, name: '猿飞日斩', work: '火影忍者' },
  { m: 2, d: 10, name: '宇智波带土', work: '火影忍者' },
  { m: 2, d: 10, name: '三笠·阿克曼', work: '进击的巨人' },
  { m: 2, d: 10, name: '松浦果南', work: 'Love Live! Sunshine!!' },
  { m: 2, d: 11, name: '艾尔海森', work: '原神' },
  { m: 2, d: 11, name: '气象学者', work: '第五人格' },
  { m: 2, d: 11, name: '南空直美', work: '死亡笔记' },
  { m: 2, d: 12, name: '蛙吹梅雨', work: '我的英雄学院' },
  { m: 2, d: 13, name: '卢娜·洛夫古德', work: '哈利·波特' },
  { m: 2, d: 13, name: '守墓人（安德鲁·克雷斯）', work: '第五人格' },
  { m: 2, d: 14, name: '调酒师（黛米·波本）', work: '第五人格' },
  { m: 2, d: 14, name: '仙道彰', work: '灌篮高手' },
  { m: 2, d: 14, name: '安城鸣子', work: '未闻花名' },
  { m: 2, d: 17, name: 'KAITO', work: 'VOCALOID · Kaito' },
  { m: 2, d: 18, name: '胡蝶忍', work: '鬼灭之刃' },
  { m: 2, d: 18, name: '红蝶（美智子）', work: '第五人格' },
  { m: 2, d: 18, name: '哈尔·莉德娜', work: '死亡笔记' },
  { m: 2, d: 19, name: '蝙蝠侠（布鲁斯·韦恩）', work: 'DC' },
  { m: 2, d: 19, name: '千手扉间', work: '火影忍者' },
  { m: 2, d: 21, name: '泉镜花', work: '文豪野犬' },
  { m: 2, d: 21, name: '后藤一里', work: '孤独摇滚！' },
  { m: 2, d: 22, name: '珊瑚宫心海', work: '原神' },
  { m: 2, d: 25, name: '山吹沙绫', work: 'BanG Dream!' },
  { m: 2, d: 25, name: '定春', work: '银魂' },
  { m: 2, d: 26, name: '谢尔顿·库珀', work: '生活大爆炸' },
  { m: 2, d: 27, name: '皮卡丘', work: '宝可梦' },
  { m: 2, d: 27, name: '春乌拉拉', work: '赛马娘' },
  { m: 2, d: 28, name: '夜神月', work: '死亡笔记' },
  { m: 2, d: 29, name: '不二周助', work: '网球王子' },
  { m: 2, d: 29, name: '骨川小夫', work: '哆啦A梦' },
  { m: 2, d: 29, name: '班尼特', work: '原神' },
  { m: 2, d: 29, name: '超人（克拉克·肯特）', work: 'DC' },
  { m: 3, d: 1, name: '芥川龙之介', work: '文豪野犬' },
  { m: 3, d: 1, name: '罗恩·韦斯莱', work: '哈利·波特' },
  { m: 3, d: 1, name: '冒险家（库特·弗兰克）', work: '第五人格' },
  { m: 3, d: 1, name: '芙莉莲', work: '葬送的芙莉莲' },
  { m: 3, d: 1, name: '莱纳·布朗', work: '进击的巨人' },
  { m: 3, d: 2, name: '巴麻美', work: '魔法少女小圆' },
  { m: 3, d: 2, name: '间桐樱', work: 'Fate/stay night' },
  { m: 3, d: 3, name: '七七', work: '原神' },
  { m: 3, d: 3, name: '久岐忍', work: '原神' },
  { m: 3, d: 3, name: '雷欧力·帕拉丁奈特', work: '全职猎人' },
  { m: 3, d: 3, name: '藤原千花', work: '辉夜大小姐想让我告白' },
  { m: 3, d: 3, name: '乔伊·达高南池', work: '玉子市场' },
  { m: 3, d: 3, name: '田中龙之介', work: '排球少年' },
  { m: 3, d: 4, name: '山治', work: '航海王' },
  { m: 3, d: 4, name: '国木田花丸', work: 'Love Live! Sunshine!!' },
  { m: 3, d: 5, name: '幸村精市', work: '网球王子' },
  { m: 3, d: 5, name: '熊猫', work: '咒术回战' },
  { m: 3, d: 6, name: '桔梗', work: '犬夜叉' },
  { m: 3, d: 7, name: '乙骨忧太', work: '咒术回战' },
  { m: 3, d: 7, name: '三月七', work: '崩坏：星穹铁道' },
  { m: 3, d: 7, name: '日暮戈薇', work: '犬夜叉' },
  { m: 3, d: 9, name: '弗兰奇', work: '航海王' },
  { m: 3, d: 9, name: '天天', work: '火影忍者' },
  { m: 3, d: 9, name: '香克斯', work: '航海王' },
  { m: 3, d: 9, name: '鹰眼米霍克', work: '航海王' },
  { m: 3, d: 10, name: '时崎狂三', work: '约会大作战' },
  { m: 3, d: 10, name: '莱姆斯·卢平', work: '哈利·波特' },
  { m: 3, d: 11, name: '摄影师（约瑟夫·德拉索恩斯）', work: '第五人格' },
  { m: 3, d: 13, name: '好歌剧', work: '赛马娘' },
  { m: 3, d: 14, name: '琴', work: '原神' },
  { m: 3, d: 14, name: '冈部伦太郎', work: '命运石之门' },
  { m: 3, d: 15, name: '我牙丸吟', work: '蓝色监狱' },
  { m: 3, d: 15, name: '园田海未', work: 'Love Live!' },
  { m: 3, d: 15, name: '田所惠', work: '食戟之灵' },
  { m: 3, d: 16, name: '电次', work: '电锯人' },
  { m: 3, d: 17, name: '医生（艾米丽·黛儿）', work: '第五人格' },
  { m: 3, d: 17, name: '尤弥尔', work: '进击的巨人' },
  { m: 3, d: 17, name: '八神太一', work: '数码宝贝大冒险' },
  { m: 3, d: 19, name: '勘探员（诺顿·坎贝尔）', work: '第五人格' },
  { m: 3, d: 20, name: '萨博', work: '航海王' },
  { m: 3, d: 20, name: '虎杖悠仁', work: '咒术回战' },
  { m: 3, d: 20, name: '冰川纱夜', work: 'BanG Dream!' },
  { m: 3, d: 20, name: '冰川日菜', work: 'BanG Dream!' },
  { m: 3, d: 21, name: '诺艾尔', work: '原神' },
  { m: 3, d: 22, name: '阿尼·利昂纳德', work: '进击的巨人' },
  { m: 3, d: 22, name: '叶隐透', work: '我的英雄学院' },
  { m: 3, d: 23, name: '赛诺', work: '原神' },
  { m: 3, d: 23, name: '美树沙耶香', work: '魔法少女小圆' },
  { m: 3, d: 23, name: '牛込里美', work: 'BanG Dream!' },
  { m: 3, d: 24, name: '菲米尼', work: '原神' },
  { m: 3, d: 26, name: '神里绫人', work: '原神' },
  { m: 3, d: 27, name: '漩涡博人', work: '博人传' },
  { m: 3, d: 27, name: '日向花火', work: '火影忍者' },
  { m: 3, d: 28, name: '春野樱', work: '火影忍者' },
  { m: 3, d: 28, name: '赤羽业', work: '暗杀教室' },
  { m: 3, d: 28, name: '德丽莎·阿波卡利斯', work: '崩坏3' },
  { m: 3, d: 30, name: '艾伦·耶格尔', work: '进击的巨人' },
  { m: 3, d: 30, name: '绫波丽', work: '新世纪福音战士' },
  { m: 4, d: 1, name: '乌索普', work: '航海王' },
  { m: 4, d: 1, name: '木之本樱', work: '魔卡少女樱' },
  { m: 4, d: 1, name: '樱木花道', work: '灌篮高手' },
  { m: 4, d: 1, name: '洁世一', work: '蓝色监狱' },
  { m: 4, d: 1, name: '弗雷德·韦斯莱', work: '哈利·波特' },
  { m: 4, d: 1, name: '乔治·韦斯莱', work: '哈利·波特' },
  { m: 4, d: 1, name: '牧绅一', work: '灌篮高手' },
  { m: 4, d: 2, name: '琳妮特', work: '原神' },
  { m: 4, d: 2, name: '古董商（戚十一）', work: '第五人格' },
  { m: 4, d: 2, name: '朝雾史织', work: '玉子市场' },
  { m: 4, d: 3, name: '青雀', work: '崩坏：星穹铁道' },
  { m: 4, d: 3, name: '空军（玛尔塔·贝坦菲尔）', work: '第五人格' },
  { m: 4, d: 3, name: '目白麦昆', work: '赛马娘' },
  { m: 4, d: 4, name: '孙悟空', work: '龙珠' },
  { m: 4, d: 4, name: '出目川仁', work: '死亡笔记' },
  { m: 4, d: 6, name: '迪希雅', work: '原神' },
  { m: 4, d: 6, name: '虎克', work: '崩坏：星穹铁道' },
  { m: 4, d: 6, name: '白胡子（爱德华·纽盖特）', work: '航海王' },
  { m: 4, d: 7, name: '铁臂阿童木', work: '铁臂阿童木' },
  { m: 4, d: 7, name: '茶渡泰虎', work: 'BLEACH' },
  { m: 4, d: 9, name: '卡维', work: '原神' },
  { m: 4, d: 10, name: '夏洛蒂', work: '原神' },
  { m: 4, d: 10, name: '美竹兰', work: 'BanG Dream!' },
  { m: 4, d: 10, name: '夜刀神十香', work: '约会大作战' },
  { m: 4, d: 11, name: '心华', work: 'VOCALOID · 中文声库' },
  { m: 4, d: 12, name: '乐正绫', work: 'Vsinger · 洛天依同企划' },
  { m: 4, d: 13, name: '雷电芽衣', work: '崩坏3' },
  { m: 4, d: 14, name: '伏特加', work: '赛马娘' },
  { m: 4, d: 14, name: '出木杉英才', work: '哆啦A梦' },
  { m: 4, d: 15, name: '程小时', work: '时光代理人' },
  { m: 4, d: 16, name: '结束祈', work: '金牌得主' },
  { m: 4, d: 16, name: '宿海仁太', work: '未闻花名' },
  { m: 4, d: 17, name: '魈', work: '原神' },
  { m: 4, d: 17, name: '渡边曜', work: 'Love Live! Sunshine!!' },
  { m: 4, d: 17, name: '火野丽', work: '美少女战士' },
  { m: 4, d: 18, name: '马狼照英', work: '蓝色监狱' },
  { m: 4, d: 18, name: '莉兹贝特', work: '刀剑神域' },
  { m: 4, d: 19, name: '桐谷直叶', work: '刀剑神域' },
  { m: 4, d: 19, name: '西木野真姬', work: 'Love Live!' },
  { m: 4, d: 20, name: '夜兰', work: '原神' },
  { m: 4, d: 20, name: '爆豪胜己', work: '我的英雄学院' },
  { m: 4, d: 20, name: '东海帝皇', work: '赛马娘' },
  { m: 4, d: 21, name: '玛薇卡', work: '原神' },
  { m: 4, d: 21, name: '喜多郁代', work: '孤独摇滚！' },
  { m: 4, d: 22, name: '嘴平伊之助', work: '鬼灭之刃' },
  { m: 4, d: 22, name: '玛奇玛', work: '电锯人' },
  { m: 4, d: 22, name: '峰田实', work: '我的英雄学院' },
  { m: 4, d: 23, name: '画家（艾格·瓦尔登）', work: '第五人格' },
  { m: 4, d: 24, name: '山本武', work: '家庭教师' },
  { m: 4, d: 25, name: '爱哭鬼（罗比·怀特）', work: '第五人格' },
  { m: 4, d: 26, name: '丹恒', work: '崩坏：星穹铁道' },
  { m: 4, d: 26, name: '开拓者', work: '崩坏：星穹铁道' },
  { m: 4, d: 27, name: '茜特菈莉', work: '原神' },
  { m: 4, d: 29, name: '中原中也', work: '文豪野犬' },
  { m: 4, d: 30, name: '迪卢克', work: '原神' },
  { m: 4, d: 30, name: '野人（穆罗）', work: '第五人格' },
  { m: 4, d: 30, name: '大石秀一郎', work: '网球王子' },
  { m: 5, d: 1, name: '李洛克', work: '火影忍者' },
  { m: 5, d: 1, name: '椎名真由理', work: '命运石之门' },
  { m: 5, d: 1, name: '渡（Watari）', work: '死亡笔记' },
  { m: 5, d: 1, name: '阿尼亚·福杰', work: '间谍过家家' },
  { m: 5, d: 1, name: '无声铃鹿', work: '赛马娘' },
  { m: 5, d: 1, name: '秋道丁次', work: '火影忍者' },
  { m: 5, d: 1, name: '康尼·斯普林格', work: '进击的巨人' },
  { m: 5, d: 2, name: '源静香', work: '哆啦A梦' },
  { m: 5, d: 2, name: '樋口一叶', work: '文豪野犬' },
  { m: 5, d: 2, name: '御坂美琴', work: '某科学的超电磁炮' },
  { m: 5, d: 2, name: '小女孩（娜娜）', work: '第五人格' },
  { m: 5, d: 2, name: '特别周', work: '赛马娘' },
  { m: 5, d: 2, name: '蒙奇·D·卡普', work: '航海王' },
  { m: 5, d: 2, name: '鹤见知利子', work: '未闻花名' },
  { m: 5, d: 3, name: '驭空', work: '崩坏：星穹铁道' },
  { m: 5, d: 4, name: '工藤新一 / 江户川柯南', work: '名侦探柯南' },
  { m: 5, d: 4, name: '桃井五月', work: '黑子的篮球' },
  { m: 5, d: 5, name: '蒙奇·D·路飞', work: '航海王' },
  { m: 5, d: 5, name: '土方十四郎', work: '银魂' },
  { m: 5, d: 5, name: '中岛敦', work: '文豪野犬' },
  { m: 5, d: 5, name: '野原新之助', work: '蜡笔小新' },
  { m: 5, d: 5, name: '中野一花 / 二乃 / 三玖 / 四叶 / 五月', work: '五等分的新娘' },
  { m: 5, d: 5, name: '小杰·富力士', work: '全职猎人' },
  { m: 5, d: 5, name: '云雀恭弥', work: '家庭教师' },
  { m: 5, d: 5, name: '中野一花', work: '五等分的新娘' },
  { m: 5, d: 5, name: '中野二乃', work: '五等分的新娘' },
  { m: 5, d: 5, name: '中野三玖', work: '五等分的新娘' },
  { m: 5, d: 5, name: '中野四叶', work: '五等分的新娘' },
  { m: 5, d: 5, name: '中野五月', work: '五等分的新娘' },
  { m: 5, d: 5, name: '砂金', work: '崩坏：星穹铁道' },
  { m: 5, d: 5, name: '圆谷光彦', work: '名侦探柯南' },
  { m: 5, d: 5, name: '吉田步美', work: '名侦探柯南' },
  { m: 5, d: 5, name: '八九寺真宵', work: '物语系列' },
  { m: 5, d: 6, name: '绮良良', work: '原神' },
  { m: 5, d: 6, name: '凪诚士郎', work: '蓝色监狱' },
  { m: 5, d: 7, name: '让·基尔希斯坦', work: '进击的巨人' },
  { m: 5, d: 7, name: '慈善家（克利切·皮尔森）', work: '第五人格' },
  { m: 5, d: 7, name: '千石抚子', work: '物语系列' },
  { m: 5, d: 8, name: '樱桃小丸子', work: '樱桃小丸子' },
  { m: 5, d: 8, name: '银狼', work: '崩坏：星穹铁道' },
  { m: 5, d: 8, name: '樱桃子', work: '樱桃小丸子' },
  { m: 5, d: 8, name: '晓美焰', work: '魔法少女小圆' },
  { m: 5, d: 8, name: '牛川四叶', work: '金牌得主' },
  { m: 5, d: 8, name: '小岛元太', work: '名侦探柯南' },
  { m: 5, d: 9, name: '千反田爱瑠', work: '冰菓' },
  { m: 5, d: 10, name: '炼狱杏寿郎', work: '鬼灭之刃' },
  { m: 5, d: 10, name: '赤木刚宪', work: '灌篮高手' },
  { m: 5, d: 11, name: '入殓师（伊索·卡尔）', work: '第五人格' },
  { m: 5, d: 11, name: '相泽周市', work: '死亡笔记' },
  { m: 5, d: 11, name: '海堂薰', work: '网球王子' },
  { m: 5, d: 15, name: '前锋（威廉·艾利斯）', work: '第五人格' },
  { m: 5, d: 15, name: '勘九郎', work: '火影忍者' },
  { m: 5, d: 18, name: '毛利兰', work: '名侦探柯南' },
  { m: 5, d: 18, name: '阿拉蕾', work: '阿拉蕾' },
  { m: 5, d: 18, name: '五郎', work: '原神' },
  { m: 5, d: 21, name: '作曲家（弗雷德里克·克雷伯格）', work: '第五人格' },
  { m: 5, d: 21, name: '真田弦一郎', work: '网球王子' },
  { m: 5, d: 22, name: '三井寿', work: '灌篮高手' },
  { m: 5, d: 24, name: '孙悟饭', work: '龙珠' },
  { m: 5, d: 25, name: '高飞', work: '迪士尼 · 高飞' },
  { m: 5, d: 27, name: '菲谢尔', work: '原神' },
  { m: 5, d: 28, name: '泉此方', work: '幸运星' },
  { m: 5, d: 28, name: '蓝波', work: '家庭教师' },
  { m: 5, d: 29, name: '钢铁侠（托尼·斯塔克）', work: '漫威' },
  { m: 5, d: 29, name: '击球手（甘吉·古普塔）', work: '第五人格' },
  { m: 5, d: 29, name: '伊地知虹夏', work: '孤独摇滚！' },
  { m: 5, d: 30, name: '长门有希', work: '凉宫春日的忧郁' },
  { m: 5, d: 30, name: '小智', work: '精灵宝可梦' },
  { m: 5, d: 31, name: '甚平', work: '航海王' },
  { m: 5, d: 31, name: '宇髄天元', work: '鬼灭之刃' },
  { m: 5, d: 31, name: '云堇', work: '原神' },
  { m: 5, d: 31, name: '菅原孝支', work: '排球少年' },
  { m: 6, d: 1, name: '甘露寺蜜璃', work: '鬼灭之刃' },
  { m: 6, d: 1, name: '荒泷一斗', work: '原神' },
  { m: 6, d: 1, name: '杂技演员（麦克·莫顿）', work: '第五人格' },
  { m: 6, d: 1, name: '杀生丸', work: '犬夜叉' },
  { m: 6, d: 1, name: '神威', work: '银魂' },
  { m: 6, d: 3, name: '乾贞治', work: '网球王子' },
  { m: 6, d: 4, name: '停云', work: '崩坏：星穹铁道' },
  { m: 6, d: 5, name: '德拉科·马尔福', work: '哈利·波特' },
  { m: 6, d: 6, name: '碇真嗣', work: '新世纪福音战士' },
  { m: 6, d: 6, name: '六道骸', work: '家庭教师' },
  { m: 6, d: 6, name: '西索', work: '全职猎人' },
  { m: 6, d: 7, name: '符玄', work: '崩坏：星穹铁道' },
  { m: 6, d: 7, name: '魅上照', work: '死亡笔记' },
  { m: 6, d: 7, name: '牧野神奈', work: '玉子市场' },
  { m: 6, d: 8, name: '那智鞠绪', work: '金牌得主' },
  { m: 6, d: 9, name: '宇智波鼬', work: '火影忍者' },
  { m: 6, d: 9, name: '唐老鸭', work: '迪士尼 · 唐老鸭' },
  { m: 6, d: 9, name: '舞女（玛格丽莎·泽莱）', work: '第五人格' },
  { m: 6, d: 9, name: '东条希', work: 'Love Live!' },
  { m: 6, d: 10, name: '诗岸', work: '平行四界 · 星尘同企划' },
  { m: 6, d: 10, name: '欧尔麦特', work: '我的英雄学院' },
  { m: 6, d: 10, name: '木野真琴', work: '美少女战士' },
  { m: 6, d: 13, name: '小原鞠莉', work: 'Love Live! Sunshine!!' },
  { m: 6, d: 15, name: '刚田武（胖虎）', work: '哆啦A梦' },
  { m: 6, d: 15, name: '君麻吕', work: '火影忍者' },
  { m: 6, d: 16, name: '温迪', work: '原神' },
  { m: 6, d: 16, name: '上鸣电气', work: '我的英雄学院' },
  { m: 6, d: 17, name: '徵羽摩柯', work: 'Vsinger · 洛天依同企划' },
  { m: 6, d: 17, name: '木暮公延', work: '灌篮高手' },
  { m: 6, d: 17, name: '恰斯卡', work: '原神' },
  { m: 6, d: 18, name: '黄濑凉太', work: '黑子的篮球' },
  { m: 6, d: 18, name: '夜神妆裕', work: '死亡笔记' },
  { m: 6, d: 18, name: '穗波玉（小玉）', work: '樱桃小丸子' },
  { m: 6, d: 19, name: '太宰治', work: '文豪野犬' },
  { m: 6, d: 19, name: '加菲猫', work: '加菲猫' },
  { m: 6, d: 20, name: '希儿', work: '崩坏：星穹铁道' },
  { m: 6, d: 20, name: '绯村剑心', work: '浪客剑心' },
  { m: 6, d: 20, name: '野原向日葵', work: '蜡笔小新' },
  { m: 6, d: 21, name: '苍穹', work: '平行四界 · 星尘同企划' },
  { m: 6, d: 21, name: '日向翔阳', work: '排球少年' },
  { m: 6, d: 21, name: '黑羽快斗', work: '魔术快斗 / 名侦探柯南' },
  { m: 6, d: 21, name: '米菲', work: '米菲兔' },
  { m: 6, d: 21, name: '宵宫', work: '原神' },
  { m: 6, d: 23, name: '索尼克', work: '刺猬索尼克' },
  { m: 6, d: 26, name: 'GUMI', work: 'VOCALOID · Megpoid' },
  { m: 6, d: 26, name: '史迪奇', work: '星际宝贝' },
  { m: 6, d: 26, name: '雷电将军', work: '原神' },
  { m: 6, d: 26, name: '八木夕凪', work: '金牌得主' },
  { m: 6, d: 26, name: '桂小太郎', work: '银魂' },
  { m: 6, d: 29, name: '胡荒亚子', work: '金牌得主' },
  { m: 6, d: 30, name: '七濑遥', work: 'Free!' },
  { m: 6, d: 30, name: '常暗踏阴', work: '我的英雄学院' },
  { m: 6, d: 30, name: '月野兔', work: '美少女战士' },
  { m: 7, d: 1, name: '夏目贵志', work: '夏目友人帐' },
  { m: 7, d: 2, name: '琴吹紬', work: '轻音少女' },
  { m: 7, d: 2, name: '佐仓杏子', work: '魔法少女小圆' },
  { m: 7, d: 3, name: '娜美', work: '航海王' },
  { m: 7, d: 3, name: '日向宁次', work: '火影忍者' },
  { m: 7, d: 3, name: '七海建人', work: '咒术回战' },
  { m: 7, d: 3, name: '芭芭拉', work: '原神' },
  { m: 7, d: 3, name: '希格雯', work: '原神' },
  { m: 7, d: 4, name: '美国队长（史蒂夫·罗杰斯）', work: '漫威' },
  { m: 7, d: 4, name: '芦户三奈', work: '我的英雄学院' },
  { m: 7, d: 6, name: '阿尔托莉雅·潘德拉贡', work: 'Fate/stay night' },
  { m: 7, d: 6, name: '麦兜', work: '麦兜故事' },
  { m: 7, d: 7, name: '犬冢牙', work: '火影忍者' },
  { m: 7, d: 7, name: '绿间真太郎', work: '黑子的篮球' },
  { m: 7, d: 7, name: '枢木朱雀', work: '叛逆的鲁路修' },
  { m: 7, d: 7, name: '奇犽·揍敌客', work: '全职猎人' },
  { m: 7, d: 7, name: '柊镜', work: '幸运星' },
  { m: 7, d: 7, name: '柊司', work: '幸运星' },
  { m: 7, d: 7, name: '毛利小五郎', work: '名侦探柯南' },
  { m: 7, d: 7, name: '战场原黑仪', work: '物语系列' },
  { m: 7, d: 8, name: '冲田总悟', work: '银魂' },
  { m: 7, d: 10, name: '漩涡玖辛奈', work: '火影忍者' },
  { m: 7, d: 10, name: '囚徒（卢卡·巴尔萨）', work: '第五人格' },
  { m: 7, d: 11, name: '言和', work: 'Vsinger · 洛天依同企划' },
  { m: 7, d: 11, name: '宇田川亚子', work: 'BanG Dream!' },
  { m: 7, d: 12, name: '洛天依', work: 'Vsinger · VOCALOID CHINA' },
  { m: 7, d: 12, name: '法罗女士', work: '第五人格' },
  { m: 7, d: 12, name: '高田清美', work: '死亡笔记' },
  { m: 7, d: 12, name: '夜神总一郎', work: '死亡笔记' },
  { m: 7, d: 13, name: '津岛善子', work: 'Love Live! Sunshine!!' },
  { m: 7, d: 13, name: '家入硝子', work: '咒术回战' },
  { m: 7, d: 14, name: '灶门炭治郎', work: '鬼灭之刃' },
  { m: 7, d: 14, name: '海绵宝宝', work: '海绵宝宝' },
  { m: 7, d: 14, name: '蜂乐回', work: '蓝色监狱' },
  { m: 7, d: 14, name: '户山香澄', work: 'BanG Dream!' },
  { m: 7, d: 15, name: '胡桃', work: '原神' },
  { m: 7, d: 15, name: '绿谷出久', work: '我的英雄学院' },
  { m: 7, d: 15, name: '近江彼方', work: 'Love Live! 虹咲学园偶像同好会' },
  { m: 7, d: 15, name: '黑崎一护', work: 'BLEACH' },
  { m: 7, d: 20, name: '及川彻', work: '排球少年' },
  { m: 7, d: 20, name: '达达利亚', work: '原神' },
  { m: 7, d: 20, name: '潮田渚', work: '暗杀教室' },
  { m: 7, d: 22, name: '矢泽妮可', work: 'Love Live!' },
  { m: 7, d: 23, name: '宇智波佐助', work: '火影忍者' },
  { m: 7, d: 23, name: '佣兵（奈布·萨贝达）', work: '第五人格' },
  { m: 7, d: 23, name: '井上织姬', work: 'BLEACH' },
  { m: 7, d: 23, name: '桃城武', work: '网球王子' },
  { m: 7, d: 24, name: '谷崎润一郎', work: '文豪野犬' },
  { m: 7, d: 25, name: '赤羽', work: '平行四界 · 星尘同企划' },
  { m: 7, d: 25, name: '牧濑红莉栖', work: '命运石之门' },
  { m: 7, d: 26, name: '墨清弦', work: 'Vsinger · 洛天依同企划' },
  { m: 7, d: 26, name: '萨沙·布劳斯', work: '进击的巨人' },
  { m: 7, d: 27, name: '可莉', work: '原神' },
  { m: 7, d: 28, name: '烟绯', work: '原神' },
  { m: 7, d: 28, name: '大空翼', work: '足球小将' },
  { m: 7, d: 28, name: '豹野飒香', work: '金牌得主' },
  { m: 7, d: 29, name: '八重神子', work: '原神' },
  { m: 7, d: 30, name: '纳威·隆巴顿', work: '哈利·波特' },
  { m: 7, d: 30, name: '弓箭手（D.M.）', work: '第五人格' },
  { m: 7, d: 31, name: '神威乐步', work: 'VOCALOID · がくっぽいど' },
  { m: 7, d: 31, name: '宫城良田', work: '灌篮高手' },
  { m: 7, d: 31, name: '哈利·波特', work: '哈利·波特' },
  { m: 8, d: 1, name: '高海千歌', work: 'Love Live! Sunshine!!' },
  { m: 8, d: 2, name: '纲手', work: '火影忍者' },
  { m: 8, d: 2, name: '火神大我', work: '黑子的篮球' },
  { m: 8, d: 3, name: '高坂穗乃果', work: 'Love Live!' },
  { m: 8, d: 3, name: '五河琴里', work: '约会大作战' },
  { m: 8, d: 4, name: '小丑（裘克）', work: '第五人格' },
  { m: 8, d: 7, name: '野比大雄', work: '哆啦A梦' },
  { m: 8, d: 7, name: '杰克', work: '第五人格' },
  { m: 8, d: 7, name: '机械师（特蕾西·列兹尼克）', work: '第五人格' },
  { m: 8, d: 7, name: '花轮和彦', work: '樱桃小丸子' },
  { m: 8, d: 8, name: '时透无一郎', work: '鬼灭之刃' },
  { m: 8, d: 8, name: '26号守卫（邦邦）', work: '第五人格' },
  { m: 8, d: 8, name: '夜久卫辅', work: '排球少年' },
  { m: 8, d: 9, name: '千切豹马', work: '蓝色监狱' },
  { m: 8, d: 10, name: '安柏', work: '原神' },
  { m: 8, d: 10, name: '史努比', work: '花生漫画' },
  { m: 8, d: 10, name: '蜘蛛侠（彼得·帕克）', work: '漫威' },
  { m: 8, d: 10, name: '三家田凉佳', work: '金牌得主' },
  { m: 8, d: 10, name: '高杉晋助', work: '银魂' },
  { m: 8, d: 11, name: '金妮·韦斯莱', work: '哈利·波特' },
  { m: 8, d: 11, name: '使徒（安）', work: '第五人格' },
  { m: 8, d: 12, name: '志村新八', work: '银魂' },
  { m: 8, d: 14, name: '服部平次', work: '名侦探柯南' },
  { m: 8, d: 15, name: '桃地再不斩', work: '火影忍者' },
  { m: 8, d: 15, name: '一辉', work: '圣斗士星矢' },
  { m: 8, d: 17, name: '日向小次郎', work: '足球小将' },
  { m: 8, d: 18, name: '布洛妮娅·扎伊切克', work: '崩坏3' },
  { m: 8, d: 19, name: '常盘绿', work: '玉子市场' },
  { m: 8, d: 21, name: '田井中律', work: '轻音少女' },
  { m: 8, d: 21, name: '小熊维尼', work: '小熊维尼' },
  { m: 8, d: 22, name: '饭田天哉', work: '我的英雄学院' },
  { m: 8, d: 23, name: '手鞠', work: '火影忍者' },
  { m: 8, d: 23, name: '悲鸣屿行冥', work: '鬼灭之刃' },
  { m: 8, d: 24, name: '珐露珊', work: '原神' },
  { m: 8, d: 24, name: '尼亚', work: '死亡笔记' },
  { m: 8, d: 25, name: '娜维娅', work: '原神' },
  { m: 8, d: 25, name: '调香师（薇拉·奈尔）', work: '第五人格' },
  { m: 8, d: 25, name: '今井莉莎', work: 'BanG Dream!' },
  { m: 8, d: 26, name: '凝光', work: '原神' },
  { m: 8, d: 26, name: '笹川了平', work: '家庭教师' },
  { m: 8, d: 27, name: '宫泽贤治', work: '文豪野犬' },
  { m: 8, d: 30, name: '国木田独步', work: '文豪野犬' },
  { m: 8, d: 31, name: '初音未来', work: 'VOCALOID · 初音ミク' },
  { m: 8, d: 31, name: '青峰大辉', work: '黑子的篮球' },
  { m: 8, d: 31, name: '莫娜', work: '原神' },
  { m: 8, d: 31, name: '阿蕾奇诺', work: '原神' },
  { m: 9, d: 1, name: '城户纱织（雅典娜）', work: '圣斗士星矢' },
  { m: 9, d: 2, name: '波雅·汉库克', work: '航海王' },
  { m: 9, d: 3, name: '我妻善逸', work: '鬼灭之刃' },
  { m: 9, d: 3, name: '哆啦A梦', work: '哆啦A梦' },
  { m: 9, d: 3, name: '大道寺知世', work: '魔卡少女樱' },
  { m: 9, d: 3, name: '青叶摩卡', work: 'BanG Dream!' },
  { m: 9, d: 4, name: '酷拉皮卡', work: '全职猎人' },
  { m: 9, d: 4, name: '明浦路司', work: '金牌得主' },
  { m: 9, d: 4, name: '近藤勋', work: '银魂' },
  { m: 9, d: 5, name: '韩吉·佐耶', work: '进击的巨人' },
  { m: 9, d: 7, name: '重云', work: '原神' },
  { m: 9, d: 8, name: '羽泽鸫', work: 'BanG Dream!' },
  { m: 9, d: 9, name: '雷泽', work: '原神' },
  { m: 9, d: 9, name: '瞬', work: '圣斗士星矢' },
  { m: 9, d: 9, name: '狱寺隼人', work: '家庭教师' },
  { m: 9, d: 10, name: '水野亚美', work: '美少女战士' },
  { m: 9, d: 12, name: '南小鸟', work: 'Love Live!' },
  { m: 9, d: 13, name: '阿贝多', work: '原神' },
  { m: 9, d: 13, name: '模木完造', work: '死亡笔记' },
  { m: 9, d: 13, name: '渚薰', work: '新世纪福音战士' },
  { m: 9, d: 14, name: '帕瓦', work: '电锯人' },
  { m: 9, d: 15, name: '旗木卡卡西', work: '火影忍者' },
  { m: 9, d: 15, name: '聂莫黎', work: '纸嫁衣' },
  { m: 9, d: 15, name: '聂莫琪', work: '纸嫁衣' },
  { m: 9, d: 18, name: '本间芽衣子', work: '未闻花名' },
  { m: 9, d: 18, name: '山田凉', work: '孤独摇滚！' },
  { m: 9, d: 19, name: '赫敏·格兰杰', work: '哈利·波特' },
  { m: 9, d: 19, name: '樱内梨子', work: 'Love Live! Sunshine!!' },
  { m: 9, d: 19, name: '长门（佩恩）', work: '火影忍者' },
  { m: 9, d: 21, name: '布洛妮娅', work: '崩坏：星穹铁道' },
  { m: 9, d: 21, name: '黑泽露比', work: 'Love Live! Sunshine!!' },
  { m: 9, d: 22, name: '奈良鹿丸', work: '火影忍者' },
  { m: 9, d: 22, name: '弗罗多·巴金斯', work: '指环王' },
  { m: 9, d: 22, name: '泽北荣治', work: '灌篮高手' },
  { m: 9, d: 23, name: '山中井野', work: '火影忍者' },
  { m: 9, d: 23, name: '八百万百', work: '我的英雄学院' },
  { m: 9, d: 27, name: '月岛萤', work: '排球少年' },
  { m: 9, d: 28, name: '布鲁克', work: '航海王' },
  { m: 9, d: 28, name: '神里绫华', work: '原神' },
  { m: 9, d: 29, name: '菊丸英二', work: '网球王子' },
  { m: 9, d: 29, name: '伊出英基', work: '死亡笔记' },
  { m: 9, d: 29, name: '猫咪老师（斑）', work: '夏目友人帐' },
  { m: 9, d: 30, name: '结城明日奈', work: '刀剑神域' },
  { m: 10, d: 1, name: '木兔光太郎', work: '排球少年' },
  { m: 10, d: 1, name: '克莱因', work: '刀剑神域' },
  { m: 10, d: 2, name: '黄昏（洛伊德·福杰）', work: '间谍过家家' },
  { m: 10, d: 3, name: '鹿目圆', work: '魔法少女小圆' },
  { m: 10, d: 4, name: '迹部景吾', work: '网球王子' },
  { m: 10, d: 4, name: '史努比', work: '花生漫画' },
  { m: 10, d: 4, name: '紫龙', work: '圣斗士星矢' },
  { m: 10, d: 4, name: '逢坂大河', work: '龙与虎' },
  { m: 10, d: 6, name: '特拉法尔加·罗', work: '航海王' },
  { m: 10, d: 7, name: '手冢国光', work: '网球王子' },
  { m: 10, d: 7, name: '桐谷和人', work: '刀剑神域' },
  { m: 10, d: 7, name: '蛇崩游大', work: '金牌得主' },
  { m: 10, d: 7, name: '约尔·福杰', work: '间谍过家家' },
  { m: 10, d: 8, name: '夏娜', work: '灼眼的夏娜' },
  { m: 10, d: 8, name: '凉宫春日', work: '凉宫春日的忧郁' },
  { m: 10, d: 8, name: '松雪集', work: '未闻花名' },
  { m: 10, d: 9, name: '紫原敦', work: '黑子的篮球' },
  { m: 10, d: 9, name: '行秋', work: '原神' },
  { m: 10, d: 9, name: '铃木园子', work: '名侦探柯南' },
  { m: 10, d: 10, name: '乐正龙牙', work: 'Vsinger · 洛天依同企划' },
  { m: 10, d: 10, name: '漩涡鸣人', work: '火影忍者' },
  { m: 10, d: 10, name: '坂田银时', work: '银魂' },
  { m: 10, d: 10, name: '心理学家（艾达·梅斯默）', work: '第五人格' },
  { m: 10, d: 10, name: '患者（埃米尔）', work: '第五人格' },
  { m: 10, d: 10, name: '夜神幸子', work: '死亡笔记' },
  { m: 10, d: 10, name: '大路饼藏', work: '玉子市场' },
  { m: 10, d: 10, name: '西谷夕', work: '排球少年' },
  { m: 10, d: 13, name: '李小狼', work: '魔卡少女樱' },
  { m: 10, d: 13, name: '芙宁娜', work: '原神' },
  { m: 10, d: 14, name: '泽田纲吉', work: '家庭教师' },
  { m: 10, d: 14, name: '埃尔文·史密斯', work: '进击的巨人' },
  { m: 10, d: 16, name: '孤爪研磨', work: '排球少年' },
  { m: 10, d: 16, name: '卫宫士郎', work: 'Fate/stay night' },
  { m: 10, d: 16, name: '休塔尔克', work: '葬送的芙莉莲' },
  { m: 10, d: 16, name: '切岛锐儿郎', work: '我的英雄学院' },
  { m: 10, d: 17, name: '西莉卡', work: '刀剑神域' },
  { m: 10, d: 18, name: '希儿·芙乐艾', work: '崩坏3' },
  { m: 10, d: 18, name: '猿飞阿斯玛', work: '火影忍者' },
  { m: 10, d: 19, name: '幻灯师', work: '第五人格' },
  { m: 10, d: 21, name: '江户川乱步', work: '文豪野犬' },
  { m: 10, d: 21, name: '绚濑绘里', work: 'Love Live!' },
  { m: 10, d: 22, name: '爱野美奈子', work: '美少女战士' },
  { m: 10, d: 23, name: '薙切绘里奈', work: '食戟之灵' },
  { m: 10, d: 23, name: '上原绯玛丽', work: 'BanG Dream!' },
  { m: 10, d: 23, name: '千手柱间', work: '火影忍者' },
  { m: 10, d: 23, name: '唐吉诃德·多弗朗明哥', work: '航海王' },
  { m: 10, d: 23, name: '狗卷棘', work: '咒术回战' },
  { m: 10, d: 24, name: '陆光', work: '时光代理人' },
  { m: 10, d: 25, name: '娜娜莉·兰佩路基', work: '叛逆的鲁路修' },
  { m: 10, d: 25, name: '优菈', work: '原神' },
  { m: 10, d: 26, name: '凑友希那', work: 'BanG Dream!' },
  { m: 10, d: 27, name: '大蛇丸', work: '火影忍者' },
  { m: 10, d: 27, name: '纳西妲', work: '原神' },
  { m: 10, d: 29, name: '枫原万叶', work: '原神' },
  { m: 10, d: 29, name: '幸平创真', work: '食戟之灵' },
  { m: 10, d: 31, name: 'L', work: '死亡笔记' },
  { m: 10, d: 31, name: '先知（伊莱·克拉克）', work: '第五人格' },
  { m: 11, d: 1, name: '凯蒂猫', work: 'Hello Kitty' },
  { m: 11, d: 1, name: '国木田独步', work: '文豪野犬' },
  { m: 11, d: 1, name: 'Hello Kitty', work: '三丽鸥 · 凯蒂猫' },
  { m: 11, d: 1, name: '星空凛', work: 'Love Live!' },
  { m: 11, d: 2, name: '香菱', work: '原神' },
  { m: 11, d: 2, name: '维迪', work: '死亡笔记' },
  { m: 11, d: 3, name: '神乐', work: '银魂' },
  { m: 11, d: 3, name: '阿尔敏·阿诺德', work: '进击的巨人' },
  { m: 11, d: 3, name: '犬夜叉', work: '犬夜叉' },
  { m: 11, d: 4, name: '阿姆罗·雷', work: '机动战士高达' },
  { m: 11, d: 5, name: 'MEIKO', work: 'VOCALOID · Meiko' },
  { m: 11, d: 6, name: '石田雨龙', work: 'BLEACH' },
  { m: 11, d: 7, name: '钉崎野蔷薇', work: '咒术回战' },
  { m: 11, d: 8, name: '相泽消太', work: '我的英雄学院' },
  { m: 11, d: 9, name: '都中伊乃户', work: '金牌得主' },
  { m: 11, d: 11, name: '罗罗诺亚·索隆', work: '航海王' },
  { m: 11, d: 11, name: '自来也', work: '火影忍者' },
  { m: 11, d: 11, name: '平泽唯', work: '轻音少女' },
  { m: 11, d: 11, name: '中野梓', work: '轻音少女' },
  { m: 11, d: 17, name: '夏亚·阿兹纳布尔', work: '机动战士高达' },
  { m: 11, d: 17, name: '橘真琴', work: 'Free!' },
  { m: 11, d: 17, name: '雕刻家（伽拉泰亚）', work: '第五人格' },
  { m: 11, d: 18, name: '米老鼠', work: '迪士尼' },
  { m: 11, d: 18, name: '米奇', work: '迪士尼 · 米老鼠' },
  { m: 11, d: 20, name: '刻晴', work: '原神' },
  { m: 11, d: 22, name: '幸运儿', work: '第五人格' },
  { m: 11, d: 23, name: '莱欧斯利', work: '原神' },
  { m: 11, d: 29, name: '玩具商（安妮·莱斯特）', work: '第五人格' },
  { m: 11, d: 29, name: '有纪（绀野木绵季）', work: '刀剑神域' },
  { m: 11, d: 30, name: '凯亚', work: '原神' },
  { m: 11, d: 30, name: '那维莱特', work: '原神' },
  { m: 11, d: 30, name: '叶月渚', work: 'Free!' },
  { m: 12, d: 1, name: '灰原哀', work: '名侦探柯南' },
  { m: 12, d: 1, name: '星矢', work: '圣斗士星矢' },
  { m: 12, d: 2, name: '甘雨', work: '原神' },
  { m: 12, d: 2, name: '哆啦美', work: '哆啦A梦' },
  { m: 12, d: 3, name: '战音Lorra', work: 'Vsinger · 洛天依同企划' },
  { m: 12, d: 3, name: '妮露', work: '原神' },
  { m: 12, d: 4, name: '惣流·明日香·兰格雷', work: '新世纪福音战士' },
  { m: 12, d: 5, name: '鲁路修·兰佩路基', work: '叛逆的鲁路修' },
  { m: 12, d: 6, name: '无穷', work: '平行四界 · 星尘同企划' },
  { m: 12, d: 7, name: '不死川实弥', work: '鬼灭之刃' },
  { m: 12, d: 7, name: '五条悟', work: '咒术回战' },
  { m: 12, d: 7, name: '若林源三', work: '足球小将' },
  { m: 12, d: 7, name: '琪亚娜·卡斯兰娜', work: '崩坏3' },
  { m: 12, d: 13, name: '梅洛', work: '死亡笔记' },
  { m: 12, d: 14, name: '松田桃太', work: '死亡笔记' },
  { m: 12, d: 16, name: '海伊', work: '平行四界 · 星尘同企划' },
  { m: 12, d: 17, name: '御影玲王', work: '蓝色监狱' },
  { m: 12, d: 20, name: '赤司征十郎', work: '黑子的篮球' },
  { m: 12, d: 20, name: '日番谷冬狮郎', work: 'BLEACH' },
  { m: 12, d: 21, name: '黑尾铁朗', work: '排球少年' },
  { m: 12, d: 21, name: '园丁（艾玛·伍兹）', work: '第五人格' },
  { m: 12, d: 21, name: '厂长（里奥·贝克）', work: '第五人格' },
  { m: 12, d: 21, name: '守夜人', work: '第五人格' },
  { m: 12, d: 22, name: '影山飞雄', work: '排球少年' },
  { m: 12, d: 22, name: '伏黑惠', work: '咒术回战' },
  { m: 12, d: 24, name: '托尼托尼·乔巴', work: '航海王' },
  { m: 12, d: 24, name: '越前龙马', work: '网球王子' },
  { m: 12, d: 24, name: '宇智波斑', work: '火影忍者' },
  { m: 12, d: 24, name: '真锅和', work: '轻音少女' },
  { m: 12, d: 25, name: '利威尔·阿克曼', work: '进击的巨人' },
  { m: 12, d: 25, name: '邮差（维克多·葛兰兹）', work: '第五人格' },
  { m: 12, d: 25, name: '弥海砂', work: '死亡笔记' },
  { m: 12, d: 27, name: '镜音铃 / 镜音连', work: 'VOCALOID · 镜音双子' },
  { m: 12, d: 27, name: '日向雏田', work: '火影忍者' },
  { m: 12, d: 27, name: '丽日御茶子', work: '我的英雄学院' },
  { m: 12, d: 27, name: '牛仔（凯文·阿尤索）', work: '第五人格' },
  { m: 12, d: 28, name: '灶门祢豆子', work: '鬼灭之刃' },
  { m: 12, d: 29, name: '提纳里', work: '原神' },
  { m: 12, d: 29, name: '跳跳虎', work: '小熊维尼' },
  { m: 12, d: 30, name: '贝特霍尔德·胡佛', work: '进击的巨人' },
  { m: 12, d: 31, name: '钟离', work: '原神' },
  { m: 12, d: 31, name: '汤姆·里德尔', work: '哈利·波特' },
  { m: 12, d: 31, name: '雷·彭伯', work: '死亡笔记' },
  { m: 12, d: 31, name: '北白川玉子', work: '玉子市场' },
  { m: 12, d: 31, name: '猫猫', work: '药屋少女的呢喃' },
  { m: 12, d: 31, name: '泽村大地', work: '排球少年' },
];
