/* 活动事件记录 · 25级初一竹坝文艺汇演 */
/* 本文件由「活动事件记录表.html」生成，可手动编辑或使用网页修改保存 */
window.ACTIVITY_DATA = {
  "title": "25级初一竹坝文艺汇演",
  "subtitle": "2025年竹坝研学文艺汇演",
  "date": "2025.12.25",
  "category": "activity",
  "items": [
    {"time": "18:28", "name": "入场", "segs": [{"duration": 1, "note": "入座"}]},
    {"time": "18:29", "name": "教官发言", "segs": [{"duration": 6, "note": "活动前演讲"}]},
    {"time": "18:35", "name": "晚会开始", "segs": [{"duration": 2, "note": "开场白"}]},
    {"time": "18:37", "name": "舞蹈：Rich Man", "segs": [{"duration": 4, "note": "慢脚舞蹈*1"}]},
    {"time": "18:42", "name": "歌曲《晴天》", "segs": [{"duration": 4, "note": "歌唱时忘词+错词"}]},
    {"time": "18:47", "name": "舞蹈：Like Gennie", "segs": [{"duration": 2, "note": "慢脚舞蹈*2"}]},
    {"time": "18:49", "name": "歌曲《心墙》", "segs": [{"duration": 4, "note": ""}]},
    {"time": "18:53", "name": "舞蹈：GEE", "segs": [{"duration": 2, "note": "慢脚舞蹈*3"}]},
    {"time": "18:55", "name": "歌曲《特别的人》", "segs": [{"duration": 5, "note": ""}]},
    {"time": "19:00", "name": "舞蹈：楼外楼", "segs": [{"duration": 4, "note": "慢脚舞蹈*4"}]},
    {"time": "19:04", "name": "歌曲《勇往直前》", "segs": [{"duration": 3, "note": "轻微忘词"}]},
    {"time": "19:07", "name": "舞蹈：You And Me", "segs": [{"duration": 4, "note": "慢脚舞蹈*5"}]},
    {"time": "19:11", "name": "歌曲《最初的回忆》", "segs": [{"duration": 4, "note": ""}]},
    {"time": "19:15", "name": "舞蹈：How You Like That", "segs": [{"duration": 4, "note": "慢脚舞蹈*6 | 首个无背景视频的跳舞节目"}]},
    {"time": "19:19", "name": "歌曲《同手同脚》", "segs": [{"duration": 4, "note": "人声：1%  伴奏：99%"}]},
    {"time": "19:23", "name": "舞蹈：一条大河", "segs": [{"duration": 4, "note": "慢脚舞蹈*7"}]},
    {"time": "19:27", "name": "歌曲《爱你没差》", "segs": [{"duration": 5, "note": ""}]},
    {"time": "19:32", "name": "舞蹈串烧", "segs": [{"duration": 4, "note": "慢脚舞蹈*8 | 慢脚串烧"}]},
    {"time": "19:36", "name": "歌曲《寻着光的方向》", "segs": [{"duration": 4, "note": "首个独唱歌曲节目"}]},
    {"time": "19:40", "name": "舞蹈：再次重逢的世界", "segs": [{"duration": 3, "note": "慢脚舞蹈*9"}]},
    {"time": "19:43", "name": "小品：校园手机风波", "segs": [{"duration": 8, "note": "首个有男节目"}]},
    {"time": "19:51", "name": "武术：双剑", "segs": [{"duration": 2, "note": "精品节目"}]},
    {"time": "19:53", "name": "舞蹈：Whiplash", "segs": [{"duration": 4, "note": "慢脚舞蹈*10"}]},
    {"time": "19:57", "name": "歌曲《晴天》", "segs": [{"duration": 5, "note": "一样的人，一样的歌，不说以为我进循环了（"}]},
    {"time": "20:02", "name": "歌舞接龙", "segs": [{"duration": 8, "note": "十班出品必属精品"}]},
    {"time": "20:10", "name": "歌曲《吻别》", "segs": [{"duration": 6, "note": "演唱：陈凌钊老师"}]},
    {"time": "20:16", "name": "歌曲《枫》", "segs": [{"duration": 5, "note": "演唱：林燕玉老师"}]},
    {"time": "20:21", "name": "合唱《最炫民族风》", "segs": [{"duration": 2, "note": "江晓进领唱"}]},
    {"time": "20:23", "name": "歌曲《成都》", "segs": [{"duration": 7, "note": "3班教官激情奉献"}]},
    {"time": "20:30", "name": "结语", "segs": [{"duration": 1, "note": ""}]},
    {"time": "20:31", "name": "生日同学祝福", "segs": [{"duration": 11, "note": ""}]},
    {"time": "20:42", "name": "离场", "segs": [{"duration": 4, "note": ""}]},
    {"time": "20:46", "name": "各班单独训人", "segs": [{"duration": 16, "note": "神秘大河马"}]},
    {"time": "21:02", "name": "回寝", "segs": [{"duration": 0, "note": ""}]}
  ]
};
